imports:
    - resource: 'parameters.yml'
    - resource: 'security.yml'
    - resource: 'services.yml'

parameters:
    locale: 'en'
    api_nasa.host: 'https://api.nasa.gov'
    api_nasa.api_key: 'N7LkblDsc5aen05FJqBQ8wU4qSdmsftwJagVK7UD'

framework:
    secret: '%secret%'
    default_locale: '%locale%'
    validation:
      enable_annotations: true
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    php_errors:
        log: true

doctrine:
    dbal:
        driver: 'pdo_mysql'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: 'UTF8'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: 'doctrine.orm.naming_strategy.underscore'
        auto_mapping: true
        dql:
            datetime_functions:
                'year': 'DoctrineExtensions\Query\Mysql\Year'
                'date_format': 'DoctrineExtensions\Query\Mysql\DateFormat'

jms_serializer:
    handlers:
        datetime:
            default_format: "c"
            default_timezone: "UTC"

fos_rest:
    param_fetcher_listener: true
    format_listener:
        enabled: true
        rules:
            - { path: ^/, priorities: [json], fallback_format: json, prefer_extension: false }
    view:
        view_response_listener: 'force'
        formats:
            json: true
